name: Release to GHR
on:
  push:
    branches:
      - staging
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SEMANTIC_RELEASE_PAT }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@dyte-in"

      - name: Set NPM_TOKEN
        run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          ENVIRONMENT: ${{ github.ref }}
          GHR: true
        run: npx semantic-release

      - name: Update staging branch
        if: |
          contains('refs/heads/main', github.ref)
        run: |
          git pull
          git stash
          git checkout staging
          git merge main
          git push --set-upstream origin staging
